# .travis.yml
dist: precise

language: php

php:
  - 7.3
  - 8.0

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE simple1;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit

notifications:  
  email:  
    recipients:  
    - sefas.alfa@gmail.com
    on_success: never  
    on_failure: always